sudo: required
services:
  - docker
  

before_install:
  - docker build -t bastien/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bastien/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  bucket_name: "elasticbeanstalk-us-east-2-873105973804"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY