version: '3.8'
services: 
  web:
    stdin_open: true
    container_name: web
    image: bastien/react:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
  tests:
    image: bastien/react:latest
    container_name: web-tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]